language: python
cache:
  apt: true
  directories:
    - $HOME/virtualenv/python2.6/lib/python2.6/site-packages/
    - $HOME/virtualenv/python2.7/lib/python2.7/site-packages/
    - $HOME/.nvm
python:
  - "2.6"
  - "2.7"
env:
  - PGVERSION=9.1
  - PGVERSION=8.4
install: ./bin/travis-install-dependencies
script: ./bin/travis-run-tests
notifications:
  irc:
    channels:
      - "irc.freenode.org#ckan"
    on_success: never
    on_failure: change
    template:
      - "%{repository} %{branch} %{commit} %{build_url} %{author}: %{message}"
after_success:
  - coveralls
